apiVersion: apps/v1
kind: Deployment
metadata:
  name: Eco-Tech
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Eco-Tech
  template:
    metadata:
      labels:
        app: Eco-Tech
    spec:
      containers:
      - name: Eco-Tech
        image: Eco-Tech:latest #colocar aqui o nome da imegem que está no docker image name:tag
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
