apiVersion: v1
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres-eco-tech
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

# O arquivo .yaml do PersistentVolumeClaim associado a um microserviço ou aplicação como o PostgreSQL:
# Garante armazenamento persistente para dados importantes.
# Facilita o gerenciamento de armazenamento em diferentes provedores (local, nuvem, etc.).
# Protege os dados da aplicação contra perda durante reinicializações de pods ou atualizações.
