apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-eco-tech
  labels:
    app: postgres-eco-tech
spec:
  serviceName: "postgresql"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-eco-tech
  template:
    metadata:
      labels:
        app: postgres-eco-tech
    spec:
      containers:
        - name: postgres-eco-tech
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: "postgres"      # Specify a username for the DB
            - name: POSTGRES_PASSWORD
              value: "eco-techmaterials" # Specify a password for the DB
            - name: POSTGRES_DB
              value: "postgres"   # Specify a database name
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data  # Mount the volume to the PostgreSQL data directory
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgres-pv-claim
