apiVersion: v1
kind: Service
metadata:
  name: postgres-eco-tech
  labels:
    app: postgres-eco-tech
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30007
  #clusterIP:   # This ensures that each pod has its own stable DNS entry (for StatefulSets)
  selector:
    app: postgres-eco-tech
